In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('HotelsManhOrl.csv')
df

,city,hotel_name,acc_type,price,hotel_star,no_of_ratings,rating,occupancy,lat_long
0,Orlando,Sonesta ES Suites Orlando - International Driv...,HOTEL,$129,3.5-star,See all 859 Hotels.com reviews,8.8,"1 room, 3 adults","['28.441941', '-81.47115']"
1,Orlando,"CoCo Key Hotel and Water Resort-Orlando, Orlando",HOTEL,$65,3-star,"See all 1,845 Hotels.com reviews",6.4,"1 room, 3 adults","['28.45468', '-81.470854']"
2,Orlando,"The Grand Orlando Resort at Celebration, Kissi...",HOTEL,$62,3.5-star,"See all 2,946 Hotels.com reviews",6.8,"1 room, 3 adults","['28.33647', '-81.534655']"
3,Orlando,Holiday Inn & Suites Across From Universal Orl...,HOTEL,$79,3-star,See all 873 Hotels.com reviews,7.8,"1 room, 3 adults","['28.477329', '-81.457288']"
4,Orlando,Howard Johnson by Wyndham Tropical Palms Kissi...,HOTEL,$30,2-star,"See all 1,423 Hotels.com reviews",5.8,"1 room, 3 adults","['28.304833', '-81.455483']"
5,Orlando,"Baymont by Wyndham Kissimmee, Kissimmee",HOTEL,$59,2.5-star,See all 433 Hotels.com reviews,6,"1 room, 3 adults","['28.303313', '-81.44829']"
6,Orlando,"Holiday Inn Orlando International Airport, Orl...",HOTEL,$88,3-star,See all 412 Hotels.com reviews,7.2,"1 room, 3 adults","['28.46027', '-81.309057']"
7,Orlando,"Clarion Inn Lake Buena Vista, a Rosen Hotel, O...",HOTEL,$150,3-star,"See all 1,417 Hotels.com reviews",8,"1 room, 3 adults","['28.387403', '-81.499148']"
8,Orlando,Days Inn & Suites by Wyndham Altamonte Springs...,HOTEL,$71,2-star,See all 523 Hotels.com reviews,5.2,"1 room, 3 adults","['28.660884', '-81.393403']"
9,Orlando,Delta Hotels by Marriott Orlando Lake Buena Vi...,HOTEL,$79,4-star,See all 815 Hotels.com reviews,8.6,"1 room, 3 adults","['28.38414', '-81.505944']"
10,Orlando,"Hyatt Regency Orlando International Airport, O...",HOTEL,$199,4-star,"See all 1,763 Hotels.com reviews",9,"1 room, 3 adults","['28.431373', '-81.305213']"
11,Orlando,"Seralago Hotel & Suites Main Gate East, Kissimmee",HOTEL,$55,3-star,"See all 3,195 Hotels.com reviews",6.2,"1 room, 3 adults","['28.332726', '-81.511951']"
12,Orlando,"Best Western Orlando East Inn & Suites, Orlando",HOTEL,$89,2.5-star,See all 563 Hotels.com reviews,7.4,"1 room, 3 adults","['28.568406', '-81.264167']"
13,Orlando,"Bryan's Spanish Cove by Diamond Resorts, Orlando",HOTEL,$148,3-star,See all 336 Hotels.com reviews,9,"1 room, 3 adults","['28.362681', '-81.501165']"
14,Orlando,"Renaissance Orlando Airport Hotel by Marriott,...",HOTEL,$118,4-star,See all 468 Hotels.com reviews,8.6,"1 room, 3 adults","['28.460379', '-81.31317']"
15,Orlando,"The Villas of Grand Cypress, Orlando",HOTEL,$223,4.5-star,See all 241 Hotels.com reviews,9.6,"1 room, 3 adults","['28.405897', '-81.528661']"
16,Orlando,"Days Inn by Wyndham N Orlando/Casselberry, Fer...",HOTEL,$85,2-star,See all 190 Hotels.com reviews,5.2,"1 room, 3 adults","['28.650083', '-81.350144']"
17,Orlando,"Avanti International Resort, Orlando",HOTEL,$74,3-star,"See all 3,905 Hotels.com reviews",7.6,"1 room, 3 adults","['28.439032', '-81.47157']"
18,Orlando,"Flamingo Waterpark Resort, Kissimmee",HOTEL,$41,3-star,From 512 reviews\nTripAdvisor Traveller Rating,6.6,"1 room, 3 adults","['28.28522', '-81.352644']"
19,Orlando,"Buena Vista Suites, Orlando",HOTEL,$88,3.5-star,"See all 2,222 Hotels.com reviews",8,"1 room, 3 adults","['28.357377', '-81.494643']"
20,Orlando,"Avanti Palms Resort and Conference Center, Orl...",HOTEL,$80,3.5-star,"See all 1,953 Hotels.com reviews",6.6,"1 room, 3 adults","['28.458296', '-81.47017']"
21,Orlando,"The Suites at Magic Tree, Kissimmee",HOTEL,NaN,3-star,See all 28 Hotels.com reviews,9.4,"1 room, 3 adults","['28.328156', '-81.590693']"
22,Orlando,Four Points by Sheraton Orlando International ...,HOTEL,$101,3.5-star,See all 627 Hotels.com reviews,8,"1 room, 3 adults","['28.462304', '-81.461441']"
23,Orlando,"Legacy Vacation Resorts-Orlando, Kissimmee",HOTEL,$66,3-star,"See all 1,487 Hotels.com reviews",7.4,"1 room, 3 adults","['28.329881', '-81.489634']"
24,Orlando,"Courtyard by Marriott Orlando Airport, Orlando",HOTEL,$74,3-star,See all 316 Hotels.com reviews,8.4,"1 room, 3 adults","['28.459671', '-81.312231']"
25,Orlando,"Disney's Port Orleans Resort - Riverside, Lake...",HOTEL,$215,3.5-star,See all 640 Hotels.com reviews,8.6,"1 room, 3 adults","['28.385062', '-81.536421']"
26,Orlando,"Marriott Orlando Downtown, Orlando",HOTEL,$130,3.5-star,See all 350 Hotels.com reviews,8,"1 room, 3 adults","['28.547271', '-81.384604']"
27,Orlando,DoubleTree by Hilton at the Entrance to Univer...,HOTEL,$98,4-star,"See all 2,017 Hotels.com reviews",8.4,"1 room, 3 adults","['28.477995', '-81.457445']"
28,Orlando,"Club Orlando, Orlando",HOTEL,NaN,2.5-star,See all 77 Hotels.com reviews,7.8,"1 room, 3 adults","['28.489394', '-81.405168']"
29,Orlando,"Sulaf Hotel LBV South, Kissimmee",HOTEL,$45,2.5-star,From 374 reviews\nTripAdvisor Traveller Rating,5.2,"1 room, 3 adults","['28.33465', '-81.48153']"
...,...,...,...,...,...,...,...,...,...
854,Manhattan,337 East Apartment #232479 Studio Bedroom 1 Ba...,HOTEL,NaN,NaN,NaN,Fabulous8.8,"1 room, 3 adults","['40.774295', '-73.952649']"
855,Manhattan,"NY016 4 Bedroom Apartment By Senstay, New York",HOTEL,NaN,3.5-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.7609', '-73.98893']"
856,Manhattan,"Hotel Indigo Lower East Side New York, New York",HOTEL,$178,4.5-star,See all 771 Hotels.com reviews,8.8,"1 room, 3 adults","['40.721736', '-73.987497']"
857,Manhattan,"Hotel 32 32, New York",HOTEL,$124,4-star,"See all 1,330 Hotels.com reviews",8,"1 room, 3 adults","['40.746207', '-73.983351']"
858,Manhattan,"Hudson River Hotel, New York",HOTEL,$109,2.5-star,See all 315 Hotels.com reviews,7.4,"1 room, 3 adults","['40.755483', '-73.99733']"
859,Manhattan,"Metro Studio Apartment in Kipsbay, New York",HOTEL,NaN,3-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.740896', '-73.981594']"
860,Manhattan,474 9th Avenue 2B. 177 3 Bedrooms 1 Bathroom A...,HOTEL,NaN,NaN,NaN,Fabulous8.8,"1 room, 3 adults","['40.754845', '-73.994908']"
861,Manhattan,"Club Quarters Hotel, opposite Rockefeller Cent...",HOTEL,$151,4-star,"See all 1,651 Hotels.com reviews",8.2,"1 room, 3 adults","['40.75982', '-73.97835']"
862,Manhattan,"Clarion Hotel Park Avenue, New York",HOTEL,$199,2.5-star,See all 69 Hotels.com reviews,7.4,"1 room, 3 adults","['40.74417', '-73.98338']"
863,Manhattan,"Night Hotel Theater District, Times Square, Ne...",HOTEL,$129,4-star,See all 558 Hotels.com reviews,7.6,"1 room, 3 adults","['40.757349', '-73.984069']"
864,Manhattan,"United Nations Apartment Hotel, New York",HOTEL,NaN,2.5-star,See all 56 Hotels.com reviews,5.4,"1 room, 3 adults","['40.751518', '-73.970371']"
865,Manhattan,East 81 Studio #232468 Studio Bedroom 1 Bathro...,HOTEL,NaN,3-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.774658', '-73.954099']"
866,Manhattan,"The Gregory Hotel, New York",HOTEL,$135,4-star,"See all 1,009 Hotels.com reviews",8,"1 room, 3 adults","['40.749875', '-73.985966']"
867,Manhattan,"414 Hotel, New York",HOTEL,$296,3.5-star,See all 90 Hotels.com reviews,9.6,"1 room, 3 adults","['40.76117', '-73.99117']"
868,Manhattan,"Soho Grand Hotel, New York",HOTEL,$199,4.5-star,See all 759 Hotels.com reviews,8.8,"1 room, 3 adults","['40.721886', '-74.004201']"
869,Manhattan,201 East 89th Street #3b. 164 1 Bedroom 1 Bath...,HOTEL,NaN,NaN,NaN,Fabulous8.8,"1 room, 3 adults","['40.780668', '-73.952036']"
870,Manhattan,"Central Harlem Renovated Apartments, New York",HOTEL,NaN,3-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.819469', '-73.937528']"
871,Manhattan,"Hilton Garden Inn New York/Manhattan-Chelsea, ...",HOTEL,$157,3.5-star,See all 968 Hotels.com reviews,8.6,"1 room, 3 adults","['40.746478', '-73.991579']"
872,Manhattan,"Washington Square Hotel, New York",HOTEL,$308,3.5-star,See all 333 Hotels.com reviews,8.8,"1 room, 3 adults","['40.73226', '-73.99867']"
873,Manhattan,"East 81 #232478 - studio Br Apts, New York",HOTEL,NaN,3-star,NaN,Very Good8.2,"1 room, 3 adults","['40.774658', '-73.954099']"
874,Manhattan,"Hello Broadway, New York",HOTEL,$195,3-star,NaN,5.8,"1 room, 3 adults","['40.74725', '-73.98776']"
875,Manhattan,"The Wagner Hotel, New York",HOTEL,$223,5-star,NaN,9,"1 room, 3 adults","['40.70552', '-74.01744']"
876,Manhattan,"The Marmara Manhattan, New York",HOTEL,$286,3.5-star,See all 335 Hotels.com reviews,8.4,"1 room, 3 adults","['40.782847', '-73.947762']"
877,Manhattan,"Freehand New York, New York",HOTEL,$129,4-star,NaN,8.8,"1 room, 3 adults","['40.73973', '-73.98442']"
878,Manhattan,329 East Apartment #232399 2 Bedrooms 1 Bathro...,HOTEL,NaN,3-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.782498', '-73.946405']"
879,Manhattan,"NY002 4 Bedroom Apartment By Senstay, New York",HOTEL,NaN,3.5-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.72218', '-74.00356']"
880,Manhattan,"Chelsea West 30th Street - 1BR Apartment, New ...",HOTEL,NaN,3.5-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.748942', '-73.993577']"
881,Manhattan,"The Inn at Irving Place, New York",HOTEL,$295,4-star,See all 111 Hotels.com reviews,9,"1 room, 3 adults","['40.736064', '-73.987251']"
882,Manhattan,"Direct Loft at 8 Rivington Street, New York",HOTEL,NaN,2.5-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.72141', '-73.99294']"
883,Manhattan,"NY063 1 Bedroom Apartment By Senstay, New York",HOTEL,NaN,3.5-star,NaN,Fabulous8.8,"1 room, 3 adults","['40.7303', '-74.00502']"

In [3]:
hotel=df.lat_long.astype(str).str.replace('\[|\]|\'','')
Hotel=hotel.to_frame()
Hotel

                  lat_long
0     28.441941, -81.47115
1     28.45468, -81.470854
2     28.33647, -81.534655
3    28.477329, -81.457288
4    28.304833, -81.455483
5     28.303313, -81.44829
6     28.46027, -81.309057
7    28.387403, -81.499148
8    28.660884, -81.393403
9     28.38414, -81.505944
10   28.431373, -81.305213
11   28.332726, -81.511951
12   28.568406, -81.264167
13   28.362681, -81.501165
14    28.460379, -81.31317
15   28.405897, -81.528661
16   28.650083, -81.350144
17    28.439032, -81.47157
18    28.28522, -81.352644
19   28.357377, -81.494643
20    28.458296, -81.47017
21   28.328156, -81.590693
22   28.462304, -81.461441
23   28.329881, -81.489634
24   28.459671, -81.312231
25   28.385062, -81.536421
26   28.547271, -81.384604
27   28.477995, -81.457445
28   28.489394, -81.405168
29     28.33465, -81.48153
..                     ...
854  40.774295, -73.952649
855     40.7609, -73.98893
856  40.721736, -73.987497
857  40.746207, -73.983351
858   40.755483, -73.99733
859  40.740896, -73.981594
860  40.754845, -73.994908
861    40.75982, -73.97835
862    40.74417, -73.98338
863  40.757349, -73.984069
864  40.751518, -73.970371
865  40.774658, -73.954099
866  40.749875, -73.985966
867    40.76117, -73.99117
868  40.721886, -74.004201
869  40.780668, -73.952036
870  40.819469, -73.937528
871  40.746478, -73.991579
872    40.73226, -73.99867
873  40.774658, -73.954099
874    40.74725, -73.98776
875    40.70552, -74.01744
876  40.782847, -73.947762
877    40.73973, -73.98442
878  40.782498, -73.946405
879    40.72218, -74.00356
880  40.748942, -73.993577
881  40.736064, -73.987251
882    40.72141, -73.99294
883     40.7303, -74.00502

[884 rows x 1 columns]

In [ ]:
#import geopyp to translate lat_long to zipcode
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="specify_your_app_name_here", timeout=100000)

p=[]
for i in Hotel['lat_long']:
    try:
        p.append((((geolocator.reverse(i)).raw)['address'])['postcode'])
    except:
        p.append('no')

In [ ]:
#append zipcode to dataframe
df['zipcode']=p

In [ ]:
hotel_new = df.loc[df['city'] == 'Manhattan']
hotel_new

In [ ]:
#export_csv = hotel_new.to_csv ('hotel_new.csv', index = None, header=True)

In [ ]:
df = df[['hotel_name','zipcode','lat_long']]

In [ ]:
df=df.loc[df['zipcode']!='no']

In [ ]:
df['zipcode'] = df['zipcode'].str[:5]
df['zipcode'] = df['zipcode'].astype(int)

In [ ]:
df=df.rename(columns={'zipcode': 'zip'})

In [ ]:
MT=[10026, 10027, 10030, 10037, 10039, 10001, 
    10011, 10018, 10019, 10020, 10036, 10029, 
    10035, 10010, 10016, 10017, 10022, 10012, 
    10013, 10014, 10004, 10005, 10006, 10007, 
    10038, 10280, 10002, 10003, 10009, 10021, 
    10028, 10044, 10065, 10075, 10128, 10023, 
    10024, 10025, 10031, 10032, 10033, 10034, 
    10040]
#source = https://www.health.ny.gov/statistics/cancer/registry/appendix/neighborhoods.htm

In [ ]:
df=df[df['zip'].isin(MT)]

In [ ]:
#export_csv = df.to_csv ('hotel.csv', index = None, header=True)